version: '3.7'

services:
  lite-hrnet:
    build: ./models/Lite-HRNet
    volumes:
      - ./data:/workspace/Lite-HRNet/data  # データをホストと共有する場合
      - ./pretrained:/workspace/Lite-HRNet/pretrained  # 学習済みモデルをホストと共有する場合