version: '3.7'

services:
  lite-hrnet:
    build: .
    volumes:
      - ./data:/workspace/Lite-HRNet/data  # データをホストと共有する場合
      - ./pretrained:/workspace/Lite-HRNet/pretrained  # 学習済みモデルをホストと共有する場合
    command: bash -c "python tools/test.py --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml --modelDir pretrained/pose_coco/pose_hrnet_w32_256x192.pth"