version: '3.7'

services:
  lite-hrnet:
    image: nvidia/cuda:11.8.0-base-ubuntu20.04
    command: nvidia-smi
    runtime: nvidia
    build: ./models/Lite-HRNet
    volumes:
      - ./models/Lite-HRNet:/workspace/Lite-HRNet
    ports:
      - "8080:8080"
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
          devices:
            - driver: nvidia
              capabilities: [compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
